[build]
builder = "nixpacks"
buildCommand = "echo 'skip build phase'"

[deploy]
startCommand = "npm install --include=dev && npm run build && npx serve dist -p $PORT --single"
restartPolicyType = "on_failure"
