import { useState, useEffect } from 'react';
import { Calendar, Activity, Zap, Database, Radio, Pencil, LogOut } from 'lucide-react';
import { useAuth } from './contexts/AuthContext';
import clsx from 'clsx';
import { WorkspaceSwitcher } from './components/WorkspaceSwitcher';
import { AccountManager } from './components/AccountManager';
import { SearchPanel } from './components/SearchPanel';
import { PostList } from './components/PostList';
import { ReviewQueue } from './components/ReviewQueue';
import { ExecutionPanel } from './components/ExecutionPanel';
import { SchedulerPanel } from './components/SchedulerPanel';
import { RadarTab } from './components/radar/RadarTab';
import { AutoPostTab } from './components/autopost/AutoPostTab';
import { useWorkspace } from './hooks/useWorkspace';
import { usePosts } from './hooks/usePosts';
import { useQueue } from './hooks/useQueue';
import { useExecution } from './hooks/useExecution';
import { Post, Draft } from './types';
import { checkHealth, getAuthStatus, AccountInfo } from './api/client';

export default function App() {
  const { user, logout } = useAuth();
  const [activeTab, setActiveTab] = useState<'workbench' | 'radar' | 'autopost'>('workbench');
  const [showScheduler, setShowScheduler] = useState(false);
  const [postingLogic, setPostingLogic] = useState('擬人幽默');
  const [replyNote, setReplyNote] = useState('');
  const [selectedPost, setSelectedPost] = useState<Post | null>(null);
  const [selectedDraft, setSelectedDraft] = useState<Draft | null>(null);
  const [backendStatus, setBackendStatus] = useState<'unknown' | 'online' | 'offline'>('unknown');
  const [threadsLoggedIn, setThreadsLoggedIn] = useState<boolean | null>(null);
  const [activeAccount, setActiveAccount] = useState<Pick<AccountInfo, 'id' | 'name' | 'username'> | null>(null);

  const {
    workspaces,
    isLoading: workspacesLoading,
    activeWorkspaceId,
    activeWorkspace,
    activeKeywords,
    switchWorkspace,
    createWorkspace,
    isSwitching,
    isCreating,
  } = useWorkspace();

  const {
    searchResults,
    isSearching,
    searchError,
    handleSearch,
    generateDrafts,
    isGeneratingDrafts,
    addToQueue,
    autoGenerateAll,
    autoGeneratedDrafts,
    autoGeneratingPostId,
    isAutoGenerating,
  } = usePosts(activeWorkspaceId);

  const {
    queue,
    count: queueCount,
    isLoading: queueLoading,
    skipPost: skipQueuePost,
    approveDraft,
    isSkipping,
    refetch: refetchQueue,
    approveAll,
    isApprovingAll,
    batchFollow,
    clearQueue,
    isClearing,
    sentPosts,
    sentCount,
    refetchSent,
    followedAccounts,
    followedCount,
    refetchFollowed,
  } = useQueue(activeWorkspaceId);

  const {
    mode: executionMode,
    setMode: setExecutionMode,
    session: executionSession,
    isStarting,
    isConfirming,
    start: startExecution,
    confirm: confirmExecution,
    cancel: cancelExecution,
  } = useExecution(activeWorkspaceId);

  const refreshAuthStatus = () => {
    getAuthStatus()
      .then(({ logged_in, active_account }) => {
        setThreadsLoggedIn(logged_in);
        setActiveAccount(active_account);
      })
      .catch(() => {});
  };

  // Check Threads auth status
  useEffect(() => {
    if (backendStatus !== 'online') return;
    refreshAuthStatus();
  }, [backendStatus]);

  // Check backend health, retry every 5s until online
  useEffect(() => {
    let timer: ReturnType<typeof setTimeout>;
    const check = () => {
      checkHealth()
        .then(() => setBackendStatus('online'))
        .catch(() => {
          setBackendStatus('offline');
          timer = setTimeout(check, 5000);
        });
    };
    check();
    return () => clearTimeout(timer);
  }, []);

  // Auto-switch to last active workspace on load
  useEffect(() => {
    const savedId = localStorage.getItem('activeWorkspaceId');
    if (savedId && workspaces.length > 0 && !activeWorkspaceId) {
      const exists = workspaces.find((w) => w.id === savedId);
      if (exists) {
        switchWorkspace(savedId).catch(console.error);
      }
    }
  }, [workspaces, activeWorkspaceId, switchWorkspace]);

  const handleSelectPost = (post: Post, draft: Draft | undefined) => {
    setSelectedPost(post);
    setSelectedDraft(draft || null);
  };

  const handleGenerateDrafts = async (params: {
    post: Post;
    style: string;
    brandVoice: string;
    length?: string;
    emojiEnabled?: boolean;
  }) => {
    const result = await generateDrafts({ ...params, postingLogic, replyNote });
    return result;
  };

  const handleApproveFromQueue = async (draftId: string) => {
    await approveDraft(draftId);
  };

  const handleApproveFromList = async (draftId: string) => {
    await approveDraft(draftId);
  };

  const brandVoice = activeWorkspace?.brand_voice || 'friendly and professional';
  const initialKeywords = activeKeywords.map((k) => k.keyword);

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 flex flex-col">
      {/* Top Bar */}
      <header className="flex-shrink-0 h-14 bg-gray-900 border-b border-gray-800 flex items-center px-4 gap-4">
        {/* Logo */}
        <div className="flex items-center gap-2 flex-shrink-0">
          <div className="w-7 h-7 bg-indigo-600 rounded-lg flex items-center justify-center">
            <Zap className="w-4 h-4 text-white" />
          </div>
          <span className="text-sm font-bold text-gray-200 hidden sm:block">Threads 工作台</span>
        </div>

        <div className="w-px h-6 bg-gray-800 hidden sm:block" />

        {/* Workspace Switcher */}
        <WorkspaceSwitcher
          workspaces={workspaces}
          activeWorkspace={activeWorkspace}
          onSwitch={switchWorkspace}
          onCreate={createWorkspace}
          isSwitching={isSwitching || workspacesLoading}
          isCreating={isCreating}
        />

        {/* Tab Switcher */}
        <div className="hidden md:flex items-center gap-0.5 p-1 bg-gray-800 rounded-lg">
          <button
            onClick={() => setActiveTab('workbench')}
            className={clsx(
              'flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-medium transition-colors',
              activeTab === 'workbench' ? 'bg-gray-700 text-gray-200' : 'text-gray-500 hover:text-gray-400'
            )}
          >
            <Zap className="w-3 h-3" />
            搜尋工作台
          </button>
          <button
            onClick={() => setActiveTab('radar')}
            className={clsx(
              'flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-medium transition-colors',
              activeTab === 'radar' ? 'bg-indigo-700 text-white' : 'text-gray-500 hover:text-gray-400'
            )}
          >
            <Radio className="w-3 h-3" />
            互追雷達
          </button>
          <button
            onClick={() => setActiveTab('autopost')}
            className={clsx(
              'flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-medium transition-colors',
              activeTab === 'autopost' ? 'bg-emerald-700 text-white' : 'text-gray-500 hover:text-gray-400'
            )}
          >
            <Pencil className="w-3 h-3" />
            自動發文
          </button>
        </div>

        {/* Workspace stats */}
        {activeWorkspace && activeTab === 'workbench' && (
          <div className="hidden md:flex items-center gap-3 text-xs text-gray-500">
            <span className="flex items-center gap-1">
              <Activity className="w-3 h-3" />
              {queueCount} 個待審核
            </span>
          </div>
        )}

        {/* Right side */}
        <div className="ml-auto flex items-center gap-3">
          {/* Backend status */}
          <div className="flex items-center gap-1.5">
            <div className={clsx(
              'w-2 h-2 rounded-full',
              backendStatus === 'online' ? 'bg-green-500' :
              backendStatus === 'offline' ? 'bg-red-500' :
              'bg-yellow-500 animate-pulse'
            )} />
            <span className="text-xs text-gray-500 hidden sm:block">
              {backendStatus === 'online' ? '後端已連線' :
               backendStatus === 'offline' ? '後端離線' :
               '連線中...'}
            </span>
          </div>

          {/* Threads 帳號管理 */}
          {threadsLoggedIn !== null && (
            <AccountManager
              activeAccount={activeAccount}
              loggedIn={!!threadsLoggedIn}
              onAccountChange={refreshAuthStatus}
            />
          )}

          {/* Scheduler Button */}
          <button
            onClick={() => setShowScheduler(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-gray-400 hover:text-gray-200 bg-gray-800 hover:bg-gray-700 rounded-lg border border-gray-700 transition-colors"
          >
            <Calendar className="w-3.5 h-3.5" />
            排程器
          </button>
        </div>

        {/* User Info */}
        {user && (
          <div className="flex items-center gap-2 ml-auto flex-shrink-0">
            {user.picture && (
              <img src={user.picture} alt={user.name} className="w-7 h-7 rounded-full" />
            )}
            <span className="text-xs text-gray-300 hidden sm:block">{user.name}</span>
            <button
              onClick={logout}
              title="登出"
              className="p-1.5 text-gray-500 hover:text-gray-300 hover:bg-gray-800 rounded transition-colors"
            >
              <LogOut className="w-3.5 h-3.5" />
            </button>
          </div>
        )}
      </header>

      {/* Main Layout */}
      {activeTab === 'radar' && (
        <RadarTab workspaceId={activeWorkspaceId} />
      )}
      {activeTab === 'autopost' && (
        <AutoPostTab workspaceId={activeWorkspaceId || ''} />
      )}
      <div className={clsx('flex-1 flex overflow-hidden', (activeTab === 'radar' || activeTab === 'autopost') && 'hidden')}>
        {/* LEFT PANEL — Search (25%) */}
        <aside className="w-64 flex-shrink-0 bg-gray-900 border-r border-gray-800 flex flex-col overflow-y-auto">
          <div className="p-4 flex-1">
            <SearchPanel
              onSearch={async (params) => {
                const results = await handleSearch(params);
                if (results && results.length > 0) {
                  autoGenerateAll(results, { postingLogic, replyNote, brandVoice });
                }
              }}
              isSearching={isSearching || isAutoGenerating}
              activeWorkspaceId={activeWorkspaceId}
              initialKeywords={initialKeywords}
              postingLogic={postingLogic}
              onPostingLogicChange={setPostingLogic}
              replyNote={replyNote}
              onReplyNoteChange={setReplyNote}
            />

            {searchError && (
              <div className="mt-3 px-3 py-2 bg-red-900/20 border border-red-800 rounded text-red-400 text-xs">
                {searchError}
              </div>
            )}
          </div>
        </aside>

        {/* CENTER — Post List (50%) */}
        <main className="flex-1 flex flex-col overflow-hidden">
          <div className="flex-1 overflow-y-auto p-4">
            {!activeWorkspaceId && (
              <div className="flex flex-col items-center justify-center h-full py-20 text-center">
                <div className="w-16 h-16 rounded-2xl bg-gray-800 flex items-center justify-center mb-4">
                  <Database className="w-8 h-8 text-gray-600" />
                </div>
                <h2 className="text-lg font-semibold text-gray-400 mb-2">歡迎使用 Threads 工作台</h2>
                <p className="text-gray-600 text-sm max-w-sm">
                  請使用上方的下拉選單建立工作區，開始搜尋並與 Threads 貼文互動。
                </p>
              </div>
            )}
            {activeWorkspaceId && (
              <PostList
                results={searchResults}
                isLoading={isSearching}
                onGenerateDrafts={handleGenerateDrafts}
                onAddToQueue={addToQueue}
                onApproveDraft={handleApproveFromList}
                isGeneratingDrafts={isGeneratingDrafts}
                brandVoice={brandVoice}
                autoGeneratedDrafts={autoGeneratedDrafts}
                autoGeneratingPostId={autoGeneratingPostId}
                isAutoGenerating={isAutoGenerating}
              />
            )}
          </div>
        </main>

        {/* RIGHT PANEL — Queue + Execution (25%) */}
        <aside className="w-72 flex-shrink-0 bg-gray-900 border-l border-gray-800 flex flex-col overflow-hidden">
          {/* Review Queue (upper half) */}
          <div className="flex-1 overflow-y-auto p-4">
            <ReviewQueue
              queue={queue}
              isLoading={queueLoading}
              onSkip={skipQueuePost || (() => Promise.resolve())}
              onApprove={handleApproveFromQueue}
              onSelectPost={handleSelectPost}
              onApproveAll={approveAll}
              onBatchFollow={batchFollow}
              onExecute={startExecution}
              onClearQueue={clearQueue}
              isSkipping={isSkipping}
              isApprovingAll={isApprovingAll}
              isClearing={isClearing}
              sentPosts={sentPosts}
              sentCount={sentCount}
              refetchSent={refetchSent}
              followedAccounts={followedAccounts}
              followedCount={followedCount}
              refetchFollowed={refetchFollowed}
              executionMode={executionMode}
              onModeChange={setExecutionMode}
              refetch={refetchQueue}
              workspaceId={activeWorkspaceId || ''}
            />
          </div>

          {/* Execution Panel (bottom) */}
          <div className="flex-shrink-0 border-t border-gray-800 p-4">
            <ExecutionPanel
              selectedPost={selectedPost}
              selectedDraft={selectedDraft}
              executionMode={executionMode}
              session={executionSession}
              isStarting={isStarting}
              isConfirming={isConfirming}
              onConfirm={confirmExecution}
              onCancel={cancelExecution}
            />
          </div>
        </aside>
      </div>

      {/* Scheduler Modal */}
      {showScheduler && (
        <SchedulerPanel
          workspaceId={activeWorkspaceId}
          onClose={() => setShowScheduler(false)}
        />
      )}
    </div>
  );
}
